### ISSUE TITLE
setup DARTH in orion

### ISSUE THREAD

**Issue by ShunLiu-NOAA** [CoryMartin-NOAA/DARTH#29]
Start working on setup DARTH in orion

**Comment by ShunLiu-NOAA** [comment]
job submit fail:
#! /bin/sh
#SBATCH --job-name=DARTH_DARTHprep_00
#SBATCH --account=da-cpu
#SBATCH --qos=batch
#SBATCH --partition=orion
#SBATCH --nodes=1-1
#SBATCH --tasks-per-node=1
#SBATCH --cpus-per-task=1
#SBATCH -t 00:05:00
#SBATCH -o /work/noaa/da/Shun.Liu/ptmp/DARTH/logs/2020102000/DARTHprep.log
#SBATCH --export=NONE
#SBATCH --comment=fc0f2069edf47c986f098a47fa6983d3
export SLURM_SET='YES'
export ROTDIR='/work/noaa/da/Shun.Liu/ptmp/DARTH'
export GESDIR='/work/noaa/stmp2/Cory.R.Martin/GFSv16para'
export HOMEDARTH='/work/noaa/da/Shun.Liu/noscrub/UFO_eval/DARTH/'
export TOPYAML='parm/sample_setup_workflow_orion.yaml'
export CDUMP='gdas'
export CDATE='2020102000'
export PDY='20201020'
export cyc='00'
export HPSSROOT='/noaa/emc-global/5year/emc.glopara/WCOSS_D/gfsv16/v16rt2'
/work/noaa/da/Shun.Liu/noscrub/UFO_eval/DARTH//jobs/rocoto/prep.sh
}}
03/12/21 13:11:14 CST :: test.xml :: WARNING: job submission failed: sbatch: error: Batch job submission failed: Invalid account or account/partition combination specified

**Comment by ShunLiu-NOAA** [comment]
add modulefile.DARTH.orion

**Comment by ShunLiu-NOAA** [comment]
'filetype: gfs', should be added to gen_yaml_fv3jedi_hofx_nomodel.py to run fv3_nomodel.

**Comment by CoryMartin-NOAA** [comment]
> 'filetype: gfs', should be added to gen_yaml_fv3jedi_hofx_nomodel.py to run fv3_nomodel.

I think it's likely we abandon any JEDI/UFO H(x) in DARTH and instead use their EWOK workflow to generate JEDI files.

**Comment by aerorahul** [comment]
@CoryMartin-NOAA 
Its likely we will end up using the EWOK workflow to validate the UFO.
If you want to get started and explore some, follow the instructions on:
https://github.com/JCSDA-internal/experiments

Most of you won't have S3 access.  There is a `no_s3` tutorial.

We can have an interactive session if it is useful for all involved.

**Comment by ShunLiu-NOAA** [comment]
OK. Will try EWOK workflow.

**Comment by ShunLiu-NOAA** [comment]
Change "nccat=$GSIDIR/exec/nc_diag_cat_serial.x" to "nccat=$GSIDIR/exec/ncdiag_cat.x" to match the name convention used in globla-workflow.

**Comment by ShunLiu-NOAA** [comment]
add "ulimit -s unlimited" to run_gsi_observer.sh
